### ISSUE TITLE
Request for Requirements File with Package Versions

### ISSUE THREAD

**Issue by Zhu-JC** [facebookresearch/lagrangian-ot#1]
Hello,

Thank you for the amazing work on this project! It has been really helpful for my current endeavors. I am trying to set up the project in my local environment, and I noticed that the requirements.txt file (or the equivalent) does not specify the versions of the required packages.

To ensure compatibility and to avoid any potential issues with different package versions(for example, the newest jax dont have attribute jax.random.PRNGKeyArray), could you please provide a requirements.txt file or equivalent with the specific versions of the packages used in this project? This would greatly assist in replicating the environment accurately.

Looking forward to your response!

**Comment by bamos** [comment]
Hi! That's great to hear. Sorry about the slightly outdated and unclear dependencies here. I don't have the original environment on hand and also had some trouble finding the right versions. I just pushed in a version [here](https://github.com/facebookresearch/lagrangian-ot/blob/main/requirements.txt) that seems to be working for me now. Can you please check that and let me know if they work for you? I'm also planning on doing a refactoring pass through the repo this week or next, and adding a few more usage instructions to the README soon. I'll let you know when I've done that as I may also try to update to the latest versions of the dependencies

**Comment by Zhu-JC** [comment]
Hi！
Thank you very much for providing the requirements file, which has been very helpful for getting started with your project. However, I encountered a couple of dependency conflicts during installation:

1. **Numpy Version Conflict**: The user requested `numpy==2.0.0`, but `basemap 1.3.7` depends on `numpy<1.25` and `>=1.22`
2. **Jax Version Conflict**: 
The user requested `jax==0.4.7`, but:
   - `flax 0.6.0` depends on `jax>=0.3.16`
   - `jaxopt 0.8.1` depends on `jax>=0.2.18`
   - `optax 0.2.2` depends on `jax>=0.1.55`
   - `ott-jax 0.4.0` depends on `jax>=0.1.67`
   - `chex 0.1.86` depends on `jax>=0.4.16`

Additionally, I've installed the latest versions of the following packages in another env:
- jax
- jaxlib
- numpy
- optax
- cloudpickle
- flax
- torch
- geomloss
- ott-jax
- hydra-core
- matplotlib
- ipython
- stochman
- gdown

And after changing `init_rng: jax.random.PRNGKeyArray` to `init_rng: jax.random.PRNGKey(0)` in `data.py`, I was able to successfully import the items listed in `train_ot.py`. But I am not sure if these changes are sufficient for running train_ot.py effectively.

**Comment by bamos** [comment]
I see, sorry about the conflicting requirements in there. I'll do a careful pass soon and fix them

**Comment by bamos** [comment]
Hi @Zhu-JC, I just refactored the code a little, updated to the latest version of ott-jax, and pushed in a hopefully conflict-free version of the requirements. Can you please pull and try these if you are still having issues with them?

**Comment by Zhu-JC** [comment]
> Hi @Zhu-JC, I just refactored the code a little, updated to the latest version of ott-jax, and pushed in a hopefully conflict-free version of the requirements. Can you please pull and try these if you are still having issues with them?

Hi! Thank you so much for making these changes promptly. 
I met some conflicts:
1.'RuntimeError: jaxlib version 0.4.30 is newer than and incompatible with jax version 0.4.16. Please update your jax and/or jaxlib packages.'. So i down the jaxlib to 0.4.16.
2.'AttributeError: module 'scipy.linalg' has no attribute 'tril''. And i down the scipy to 1.12.0
3.import flax: ImportError: cannot import name 'ShapedArray' from 'jax'. And i down jax and jaxlib to 0.4.13
After these, it seems no import error to me.
Thanks a lot for your work!

**Comment by bamos** [comment]
Thank you for checking. The jax version seems tricky to get right in the requirements because I also have it set with slightly conflicting versions forced by the CUDA/cudnn library versions on my system. I just updated `requirements.txt` with your corrected versions, and added a note to the README that it's also important to run jax with CUDA (which may introduce a few conflicts).

I also added a few more details to the README about running the code in all of the settings from our paper. Please let me know if everything's working for you or if there are any other clarifications that would be useful!

**Comment by Zhu-JC** [comment]
> Thank you for checking. The jax version seems tricky to get right in the requirements because I also have it set with slightly conflicting versions forced by the CUDA/cudnn library versions on my system. I just updated `requirements.txt` with your corrected versions, and added a note to the README that it's also important to run jax with CUDA (which may introduce a few conflicts).
> 
> I also added a few more details to the README about running the code in all of the settings from our paper. Please let me know if everything's working for you or if there are any other clarifications that would be useful!

Hello! When i run python ./train_ot.py geometry=gsb_gmm, i got "In 'hydra/config': Could not find 'hydra/launcher/submitit_slurm'". So i run "pip install hydra-submitit-launcher". After that, i can successfully run your project!

**Comment by bamos** [comment]
Great to hear, thank you for checking! The `submitit_slurm` references should also be removed in the main branch now too
